### ISSUE TITLE
Failed to get final advertise address

### ISSUE THREAD

**Issue by jekor** [tgres/tgres#16]
Using the default config (except a different db connection string), I get the following error:

```
Error initializing cluster, exiting: Failed to get final advertise address: %!v(MISSING)
```

To fix this, I set the `TGRES_BIND` environment variable (to "0.0.0.0" to match the config), but I had to read the source to find it and I'm not sure it's the correct fix.

**Comment by grisha** [comment]
I'm not sure what is going on here, any more detail would be appreciated, I'll see if I can reproduce it.

This also exposes a memberlist tiny bug - it's missing an argument to `fmt.Errorf`, I created an issue for it: https://github.com/hashicorp/memberlist/issues/116

**Comment by grisha** [comment]
@jekor it would help if you edited your `$GOPATH/src/github.com/memberlist/memberlist.go` and changed line 337 to `return fmt.Errorf("Failed to get final advertise address: %v", err)` to see what the actual error is.

**Comment by grisha** [comment]
Closing this - there is now some re-try logic that seems to work around this problem even though I still do not quite understand what it is, but that's a memberlist issue, not ours.
