### ISSUE TITLE
provide a way to delete data sources

### ISSUE THREAD

**Issue by jekor** [tgres/tgres#17]
I'm not sure if this is desirable with the way tgres stores data, but it would be helpful to have a command (or postgresql function) to delete a data source (or documentation if this exists already). #

**Comment by grisha** [comment]
Deleting a data source would definitely be very useful. You can sort of delete a DS right now by simply running a `DELETE` SQL and it should wipe the corresponding RRAs, etc via `CASCADE`, but a running instance of Tgres wouldn't know about so I'm not sure what the consequences of that would be. So probably a better way is to provide a way to delete a DS via Tgres. 

As far as database organization - a deleted DS would create a "gap" in the time series array, but that's not a big deal. We could also have a way by which the next new DS takes use of the gap. If there is a lot of deleting going on, then in theory there could be some way to "defrag" the database space if needed.

Related to that is also an ability to rename a DS.

**Comment by graf0** [comment]
Maybe tgres should use notify/listen from postgres, then trigger after delete could simply notify deamon about changes
