### ISSUE TITLE
The gap / backfill problem.

### ISSUE THREAD

**Issue by grisha** [tgres/tgres#18]
If we have a series that has not received a data point for a while (i.e. a number of steps), the next data point will cause RRD to fill the gap. This will in turn cause a lot of rows to get updated in the database. If there are _many_ such "stale" series suddenly brought back to life, it causes the vcache to temporarily grow very large followed by a lot of db activity. On a busy set up it is sufficient to leave Tgres stopped for an hour or two to experience this, and there is no easy work-around, it's possible to end up in a situation when Tgres just cannot be started back up. As a band-aid we could impose a limit on the vcache size, but that doesn't really solve the problem.

One potential way to solve this problem is to not back-fill if the gap exceeds a certain size. The problem is that due to the round-robin nature of our storage, we cannot simply leave slots untouched because they may have previous data in them ("shadow data"). The way to address the sub-problem of shadow data is to add some kind of a version to each data point. Whisper, for example, stores the timestamp, and so if a data point timestamp is outside the range expected, it can be ignored as "expired". 

Adding a timestamp to seems like a lot of extra data for not much gain, but alternatively it could be a 1 byte version. 1 byte would prevent shadow data across 256 iterations of the db, which seems sufficient. If an RRA has been stale for more than 256 times its span, we could have a special rule that prevents its update (i.e. you have to delete and re-create it, for example).

This would be another backwards-incompatible db schema change, alas. 

Edit: Smallest PG type appears to be SMALLINT which is 2 bytes.

**Comment by grisha** [comment]
Some more research on this.

The `dp` array could be an array of a composite type. For example:
```
CREATE TYPE datapoint AS (
  val DOUBLE PRECISION,
  ver SMALLINT
);

CREATE TABLE test (
       i INT NOT NULL,
       dp datapoint[] NOT NULL DEFAULT '{}'
);

INSERT INTO test (i, dp) VALUES (1, ARRAY[(1.234,2)::datapoint]);
INSERT INTO test (i, dp) VALUES (2, '{"(2.345,3)","(-0.234,3)"}');

SELECT * FROM test;
 i |             dp             
---+----------------------------
 1 | {"(1.234,2)"}
 2 | {"(2.345,3)","(-0.234,3)"}
(2 rows)
```

But I don't know how well composite types are supported by the pq driver, as well as what sort of complications this causes for the view and all our SQL.

Another alternative: add an array column `versions` to the `ts` table as an array of smallint. This might be cleaner and possibly even somewhat backwards compatible.

**Comment by lumberg72** [comment]
I don't know if this useful or not... but boolean is a 1 byte data type.
https://www.postgresql.org/docs/9.6/static/datatype-boolean.html

**Comment by grisha** [comment]
Boolean wouldn't cut it in this case, we need something that can be incremented for a short range. If PG had a 1-byte integer giving us 256 versions that'd be golden, but alas...
