### ISSUE TITLE
Connecting to Grafana

### ISSUE THREAD

**Issue by rvanrooy** [tgres/tgres#20]
Hi. This is more a question about documentation.

I see you've had success using tgres as a data source for Grafana. Did you have to do anything special to get this working? 

I really agree with your premise that time series should be stored in a relational database, so I'm hoping I can get this working.

**Comment by grisha** [comment]
@rvanrooy you don't need to do anything special, Tgres will listen on an HTTP port which pretends to be Graphite. There are minor differences in that Tgres does not support support some of the more obscure Graphite functions, but I don't think most people encounter that. There is a Tgres Grafana plugin but at this point it's not required. May be eventually, if Tgres and Graphite functions diverge it will become useful.

**Comment by rvanrooy** [comment]
Thanks, I managed to get it working, was really just an issue with timestamps.

Thanks!
