### ISSUE TITLE
Add foreground option for Docker use

### ISSUE THREAD

**Issue by johann8384** [tgres/tgres#4]
I'd like to use this tool, and I'm happy to setup a Dockerfile for it.

If you want to add a branch where you are doing the WIP receiver refactor, I can contribute on that also. Or I can wait until you're at a milestone.

**Comment by grisha** [comment]
It's all in master at this point - so whatever works for you! Thanks! Foreground option is def. a good idea.

**Comment by grisha** [comment]
On a second thought... tgres currently runs in the foreground, i.e. there is no background option, which needs to be addressed (it should probably default to daemon, and there should be a foreground option). But it should work with Docker as it is presently I think.

**Comment by johann8384** [comment]
Ok, I think it behaved differently when I tried it last week, but I am
inclined to say you are the expert on the matter.

I will check it out tomorrow and do whichever is not happening.

**Comment by grisha** [comment]
oops this wasn't supposed to close
