### ISSUE TITLE
averageSeries with wildcard causes 'invalid memory address or nil pointer dereference'

### ISSUE THREAD

**Issue by a1exsh** [tgres/tgres#7]
We have two metrics:
```
local.test.a
local.test.b
```

We are producing some random data points for these metrics.  When we are trying to render one of them, everything looks fine:
```
$ curl -s "http://localhost:8888/render?target=averageSeries(local.test.a)&from=$( date +%s --date=-5min )&maxDataPoints=10&format=json"
[
{"target": "averageSeries(local.test.a)", "datapoints": [
[null, 1482321120],[4.733333333333334, 1482321180],[5.383333333333332, 1482321240],[4.783333333333332, 1482321300],[4.1833333333333345, 1482321360],[5.216666666666667, 1482321420]]}]
```

But if we try to have average across both metrics:
```
$ curl -s "http://localhost:8888/render?target=averageSeries(local.test.*)&from=$( date +%s --date=-5min )&maxDataPoints=10&format=json"
```

then we are getting an error and the following stack trace in the logs:
```
[9] 2016/12/21 11:51:26 http: panic serving 172.17.0.1:54804: runtime error: invalid memory address or nil pointer dereference
goroutine 14 [running]:
net/http.(*conn).serve.func1(0xc820092a80)
	/usr/lib/go-1.6/src/net/http/server.go:1389 +0xc1
panic(0xaedd80, 0xc820010080)
	/usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
database/sql.(*Rows).Close(0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/database/sql/sql.go:1863 +0x28
github.com/tgres/tgres/serde.(*dbSeries).Close(0xc820109ba0, 0x0, 0x0)
	/usr/local/src/github.com/tgres/tgres/serde/dbseries.go:190 +0x34
github.com/tgres/tgres/dsl.(*SeriesList).Close(0xc820388600, 0x0, 0x0)
	/usr/local/src/github.com/tgres/tgres/dsl/funcs.go:560 +0xa6
github.com/tgres/tgres/http.GraphiteRenderHandler.func1(0x7f849dfd1f70, 0xc820109520, 0xc8201180e0)
	/usr/local/src/github.com/tgres/tgres/http/graphite.go:122 +0x1243
net/http.HandlerFunc.ServeHTTP(0xc820232010, 0x7f849dfd1f70, 0xc820109520, 0xc8201180e0)
	/usr/lib/go-1.6/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc82000b710, 0x7f849dfd1f70, 0xc820109520, 0xc8201180e0)
	/usr/lib/go-1.6/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820236000, 0x7f849dfd1f70, 0xc820109520, 0xc8201180e0)
	/usr/lib/go-1.6/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820092a80)
	/usr/lib/go-1.6/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/lib/go-1.6/src/net/http/server.go:2137 +0x44e
```

Could it be that in `dbseries.go:190` we are trying to call `Close()` on a nil pointer?

**Comment by grisha** [comment]
Indeed it is calling close on a nil pointer, thanks for catching it! Now the question is _why_? Looking into it...

**Comment by a1exsh** [comment]
@grisha thank you for fast response, that really did fix the crash for us!

Now that we looked again into the metrics we have in the test instance, it seems that there were also something else that matches our wildcard query:
```
tgres=# tgres=# select * from ds where name like 'local%';
 id |       name        | step_ms | heartbeat_ms |       lastupdate       | value | duration_ms 
----+-------------------+---------+--------------+------------------------+-------+-------------
 26 | local.test.test1  |   60000 |      7200000 |                        |   NaN |           0
 30 | local.acid.team   |   60000 |      7200000 | 2016-12-21 13:27:02+00 |     1 |        2000
 29 | local.test.sample |   60000 |      7200000 | 2016-12-21 11:08:00+00 |   NaN |           0
 31 | local.test.a      |   60000 |      7200000 | 2016-12-21 13:27:05+00 |     2 |        5000
 32 | local.test.b      |   60000 |      7200000 | 2016-12-21 13:27:00+00 |   NaN |           0
(5 rows)
```
Could this explain the nil db cursor?  Another point is that we don't have a crash now, but we don't get any data points, most probably also due to these other "empty" metrics:
```
$ curl -s "http://localhost:8888/render?target=averageSeries(local.test.*)&from=$( date +%s --date=-5min )&maxDataPoints=10&format=json"
[
{"target": "averageSeries(local.test.*)", "datapoints": [
]}]
```
Is this expected?

Thanks again.

**Comment by grisha** [comment]
So the way Average works (actually this applies to anything that combines multiple series) is that it iterates over the series data similar with Next(), and when a Next() encounters the end, iteration stops. This means that the resulting series is a long as your shortest series, and in this particular case I'm guessing `local.test.test1` has no data because its `lastupdate` is null. 

Now whether that's right or wrong - I don't know, I'm inclined to say that this is the correct behavior, because otherwise we'd have to come up with a "default value" for the empty series, e.g. NaN, but then what's an average of anything containining a NaN - that'd be a NaN, so that won't work. A zero wouldn't be right either I think.

The reason the `nil` pointer happened was that the iteration ended before `Next()` was called for the first time on some of the series (the first call to Next() is what sets that pointer).

**Comment by a1exsh** [comment]
Thanks, that makes sense. I still wonder how did we manage to get a series without any data points...
