### ISSUE TITLE
Value Lists not supported

### ISSUE THREAD

**Issue by a1exsh** [tgres/tgres#8]
It seems that "Value Lists" syntax `{foo,bar,...}` from http://graphite.readthedocs.io/en/latest/render_api.html#paths-and-wildcards is not supported by tgres.

When testing with curl (note that curl has its own idea about interpreting curly braces, so we need to escape them):
```
$ curl -v 'http://localhost:8888/render?target=local.random.\{a,b\}&maxDataPoints=10&from=-1h'
```
I'm getting the following error in the log:
```
[8] 2016/12/22 15:12:32 RenderHandler(): Error parsing "group(\"local.random.\"{a,b})": 1:22: missing ',' in argument list
```

This seems to be caused by the fact that we use go parser here: https://github.com/tgres/tgres/blob/master/dsl/dsl.go#L45

**Comment by grisha** [comment]
Correct - in my universe I couldn't find any evidence of actual use of it, and it seemed tricky to implement, so I put it aside for "later" whatever that means... Feel free to contribute :)

**Comment by a1exsh** [comment]
@grisha there you go: #9 :-)

**Comment by grisha** [comment]
Looks good to me, clever use of recursion, merged!
